// models/MatlabExporter.js
// Generates ready-to-run MATLAB code for the robot kinematic chain.
// Extends BaseExporter.
//   numeric()  - uses native MATLAB arrays for FK, frames, Jacobian, and reference points
//   symbolic() - uses the Symbolic Math Toolbox with syms q1 q2 ... real
import BaseExporter from './BaseExporter.js';

class MatlabExporter extends BaseExporter {

    numeric(rows, points) {
        const n = this.actuatedCount(rows);
        let qi = 1;

        const dhParams = rows.map((row, i) => {
            const isR = row.jointType === 'R';
            const isP = row.jointType === 'P';
            const lines = [`    % Link ${i+1} - ${isR ? 'Revolute' : 'Prismatic'}${row.actuated ? '' : ' (passive)'}`];
            lines.push(`    alpha${i} = ${this.fmt(row.alpha)};`);
            lines.push(`    a${i}     = ${this.fmt(row.a)};`);
            if (isP && row.actuated) {
                lines.push(`    d${i+1}     = q(${qi}) + ${this.fmt(row.d)};`);
                lines.push(`    theta${i+1} = ${this.fmt(row.theta)};`);
                qi++;
            } else if (isR && row.actuated) {
                lines.push(`    d${i+1}     = ${this.fmt(row.d)};`);
                lines.push(`    theta${i+1} = q(${qi}) + ${this.fmt(row.theta)};`);
                qi++;
            } else {
                lines.push(`    d${i+1}     = ${this.fmt(row.d)};`);
                lines.push(`    theta${i+1} = ${this.fmt(row.theta)};`);
            }
            return lines.join('\n');
        }).join('\n\n');

        const matrices = rows.map((_, i) => [
            `    ct${i+1} = cos(theta${i+1}); st${i+1} = sin(theta${i+1});`,
            `    ca${i}  = cos(alpha${i});  sa${i}  = sin(alpha${i});`,
            `    T${i}${i+1} = [ct${i+1}, -st${i+1}, 0, a${i}; st${i+1}*ca${i}, ct${i+1}*ca${i}, -sa${i}, -sa${i}*d${i+1}; st${i+1}*sa${i}, ct${i+1}*sa${i}, ca${i}, ca${i}*d${i+1}; 0, 0, 0, 1];`,
        ].join('\n')).join('\n\n');

        const chain = rows.length === 1
            ? `    T = T01;`
            : `    T = T01;\n` + rows.slice(1).map((_, i) => `    T = T * T${i+1}${i+2};`).join('\n');

        const framesCode = [
            'end', '',
            `function frames = forward_kinematics_frames(${n > 0 ? 'q' : ''})`,
            '    frames = {eye(4)};',
            ...rows.map((_, i) => `    frames{end+1} = frames{end} * T${i}${i+1};`),
        ].join('\n');

        const jacobianCode = [
            '', `function J = jacobian(${n > 0 ? 'q' : ''})`,
            `    % Geometric Jacobian J(q) in R^(6x${rows.length})`,
            `    frames = forward_kinematics_frames(${n > 0 ? 'q' : ''});`,
            `    o_n = frames{end}(1:3, 4);`,
            `    Jv = zeros(3, ${rows.length}); Jw = zeros(3, ${rows.length});`,
            ...rows.map((row, i) => [
                `    z${i} = frames{${i+1}}(1:3, 3); o${i} = frames{${i+1}}(1:3, 4);`,
                row.jointType === 'R'
                    ? `    Jv(:, ${i+1}) = cross(z${i}, o_n - o${i}); Jw(:, ${i+1}) = z${i};`
                    : `    Jv(:, ${i+1}) = z${i}; Jw(:, ${i+1}) = zeros(3, 1);`,
            ].join('\n')),
            `    J = [Jv; Jw];`, 'end',
        ].join('\n');

        const pointsCode = points.length === 0 ? '' : [
            '', `function pts = point_positions(${n > 0 ? 'q' : ''})`,
            `    frames = forward_kinematics_frames(${n > 0 ? 'q' : ''});`,
            ...points.map(p => [
                `    p${p.label}_local = [${this.fmt(p.x)}; ${this.fmt(p.y)}; ${this.fmt(p.z)}; 1];`,
                `    p${p.label} = frames{${p.frameIndex + 1}} * p${p.label}_local;`,
                `    pts.${p.label} = p${p.label}(1:3);`,
            ].join('\n')),
            'end',
        ].join('\n');

        return [
            '% Forward kinematics + Jacobian - Craig DH convention',
            `% Robot: ${rows.length} link(s), ${n} actuated joint(s)`,
            '% Generated by DHViz', '',
            `function T = forward_kinematics(${n > 0 ? 'q' : ''})`,
            dhParams, '',
            matrices, '',
            chain,
            framesCode,
            jacobianCode,
            pointsCode,
        ].join('\n');
    }

    symbolic(rows, points) {
        const n = this.actuatedCount(rows);
        const qSyms = Array.from({length: n}, (_, i) => `q${i+1}`);
        const symsDecl = n > 0 ? `    syms ${qSyms.join(' ')} real` : '    % No actuated joints';

        let qi = 1;
        const dhParams = rows.map((row, i) => {
            const isR = row.jointType === 'R';
            const isP = row.jointType === 'P';
            const lines = [`    % Link ${i+1} - ${isR ? 'Revolute' : 'Prismatic'}${row.actuated ? '' : ' (passive)'}`];
            lines.push(`    alpha${i} = sym(${this.fmt(row.alpha)});`);
            lines.push(`    a${i}     = sym(${this.fmt(row.a)});`);
            if (isP && row.actuated) {
                const off = Math.abs(row.d) < 1e-10 ? '' : ` + sym(${this.fmt(row.d)})`;
                lines.push(`    d${i+1}     = q${qi}${off};`);
                lines.push(`    theta${i+1} = sym(${this.fmt(row.theta)});`);
                qi++;
            } else if (isR && row.actuated) {
                lines.push(`    d${i+1}     = sym(${this.fmt(row.d)});`);
                const off = Math.abs(row.theta) < 1e-10 ? '' : ` + sym(${this.fmt(row.theta)})`;
                lines.push(`    theta${i+1} = q${qi}${off};`);
                qi++;
            } else {
                lines.push(`    d${i+1}     = sym(${this.fmt(row.d)});`);
                lines.push(`    theta${i+1} = sym(${this.fmt(row.theta)});`);
            }
            return lines.join('\n');
        }).join('\n\n');

        const matrices = rows.map((_, i) => [
            `    T${i}${i+1} = [cos(theta${i+1}), -sin(theta${i+1}), 0, a${i};`,
            `               sin(theta${i+1})*cos(alpha${i}), cos(theta${i+1})*cos(alpha${i}), -sin(alpha${i}), -sin(alpha${i})*d${i+1};`,
            `               sin(theta${i+1})*sin(alpha${i}), cos(theta${i+1})*sin(alpha${i}),  cos(alpha${i}),  cos(alpha${i})*d${i+1};`,
            `               0, 0, 0, 1];`,
            `    T${i}${i+1} = simplify(T${i}${i+1});`,
        ].join('\n')).join('\n\n');

        const chain = rows.length === 1
            ? `    T = T01;`
            : `    T = T01;\n` + rows.slice(1).map((_, i) => `    T = simplify(T * T${i+1}${i+2});`).join('\n');

        const jacobianSymCode = [
            '', 'function J = jacobian_symbolic()',
            `    % Symbolic Jacobian J(q) in R^(6x${rows.length})`,
            symsDecl,
            '    frames = forward_kinematics_symbolic(true);',
            `    o_n = frames{end}(1:3, 4);`,
            `    Jv = sym(zeros(3, ${rows.length})); Jw = sym(zeros(3, ${rows.length}));`,
            ...rows.map((row, i) => [
                `    z${i} = frames{${i+1}}(1:3, 3); o${i} = frames{${i+1}}(1:3, 4);`,
                row.jointType === 'R'
                    ? `    Jv(:, ${i+1}) = simplify(cross(z${i}, o_n - o${i})); Jw(:, ${i+1}) = z${i};`
                    : `    Jv(:, ${i+1}) = z${i}; Jw(:, ${i+1}) = sym(zeros(3, 1));`,
            ].join('\n')),
            `    J = simplify([Jv; Jw]);`, 'end',
        ].join('\n');

        const pointsCode = points.length === 0 ? '' : [
            '', 'function pts = point_positions_symbolic()',
            symsDecl,
            '    frames = forward_kinematics_symbolic(true);',
            ...points.map(p => [
                `    p${p.label}_local = [sym(${this.fmt(p.x)}); sym(${this.fmt(p.y)}); sym(${this.fmt(p.z)}); 1];`,
                `    p${p.label} = simplify(frames{${p.frameIndex + 1}} * p${p.label}_local);`,
                `    pts.${p.label} = p${p.label}(1:3);`,
            ].join('\n')),
            'end',
        ].join('\n');

        const framesCode = [
            '    if nargin > 0 && return_frames',
            "        frames = {eye(4, 'sym')};",
            ...rows.map((_, i) => `        frames{end+1} = simplify(frames{end} * T${i}${i+1});`),
            '        T = frames;',
            '    end', 'end',
            pointsCode,
            jacobianSymCode,
        ].join('\n');

        return [
            '% Symbolic forward kinematics + Jacobian - Craig DH convention',
            `% Robot: ${rows.length} link(s), ${n} actuated joint(s)`,
            '% Requires: Symbolic Math Toolbox',
            '% Generated by DHViz', '',
            'function T = forward_kinematics_symbolic(return_frames)',
            '    if nargin < 1, return_frames = false; end',
            symsDecl, '',
            dhParams, '',
            matrices, '',
            chain,
            framesCode,
        ].join('\n');
    }
}

export default MatlabExporter;