// models/PythonExporter.js
// Generates ready-to-run Python code for the robot kinematic chain.
// Extends BaseExporter.
//   numeric()  - uses NumPy for FK, frames, Jacobian, and reference point positions
//   symbolic() - uses SymPy with q_i as symbolic variables
import BaseExporter from './BaseExporter.js';

class PythonExporter extends BaseExporter {

    numeric(rows, points) {
        const n = this.actuatedCount(rows);
        let qi = 1;

        const dhParams = rows.map((row, i) => {
            const isR = row.jointType === 'R';
            const isP = row.jointType === 'P';
            const lines = [`    # Link ${i+1} - ${isR ? 'Revolute' : 'Prismatic'}${row.actuated ? '' : ' (passive)'}`];
            lines.push(`    alpha${i} = ${this.fmt(row.alpha)}   # rad`);
            lines.push(`    a${i}     = ${this.fmt(row.a)}   # m`);
            if (isP && row.actuated) {
                lines.push(`    d${i+1}     = q[${qi-1}] + ${this.fmt(row.d)}`);
                lines.push(`    theta${i+1} = ${this.fmt(row.theta)}`);
                qi++;
            } else if (isR && row.actuated) {
                lines.push(`    d${i+1}     = ${this.fmt(row.d)}`);
                lines.push(`    theta${i+1} = q[${qi-1}] + ${this.fmt(row.theta)}`);
                qi++;
            } else {
                lines.push(`    d${i+1}     = ${this.fmt(row.d)}`);
                lines.push(`    theta${i+1} = ${this.fmt(row.theta)}`);
            }
            return lines.join('\n');
        }).join('\n\n');

        const matrices = rows.map((_, i) => [
            `    ct${i+1}, st${i+1} = np.cos(theta${i+1}), np.sin(theta${i+1})`,
            `    ca${i},  sa${i}  = np.cos(alpha${i}),  np.sin(alpha${i})`,
            `    T${i}${i+1} = np.array([`,
            `        [ ct${i+1},          -st${i+1},           0,        a${i}          ],`,
            `        [ st${i+1}*ca${i},    ct${i+1}*ca${i},   -sa${i},  -sa${i}*d${i+1} ],`,
            `        [ st${i+1}*sa${i},    ct${i+1}*sa${i},    ca${i},   ca${i}*d${i+1} ],`,
            `        [ 0,               0,               0,        1             ]`,
            `    ])`,
        ].join('\n')).join('\n\n');

        const chain = rows.length === 1
            ? `    T = T01`
            : `    T = T01\n` + rows.slice(1).map((_, i) => `    T = T @ T${i+1}${i+2}`).join('\n');

        const framesCode = [
            '', '',
            'def forward_kinematics_frames(q):',
            '    """Returns list of frame transforms [T_0, T_01, ...]"""',
            '    frames = [np.eye(4)]',
            ...rows.map((_, i) => `    frames.append(frames[-1] @ T${i}${i+1})`),
            '    return frames',
        ].join('\n');

        const jacobianCode = [
            '', '',
            `def jacobian(${n > 0 ? 'q' : ''}):`,
            `    """Geometric Jacobian J(q) in R^(6x${rows.length})"""`,
            `    frames = forward_kinematics_frames(${n > 0 ? 'q' : ''})`,
            `    o_n = frames[-1][:3, 3]`,
            `    Jv = np.zeros((3, ${rows.length}))`,
            `    Jw = np.zeros((3, ${rows.length}))`,
            ...rows.map((row, i) => [
                `    z${i} = frames[${i}][:3, 2]`,
                `    o${i} = frames[${i}][:3, 3]`,
                row.jointType === 'R'
                    ? `    Jv[:, ${i}] = np.cross(z${i}, o_n - o${i})\n    Jw[:, ${i}] = z${i}`
                    : `    Jv[:, ${i}] = z${i}\n    Jw[:, ${i}] = np.zeros(3)`,
            ].join('\n')),
            `    return np.vstack([Jv, Jw])`,
        ].join('\n');

        const pointsCode = points.length === 0 ? '' : [
            '', '',
            'def point_positions(q):',
            `    """Positions of reference points in base frame {0}"""`,
            '    T_frames = forward_kinematics_frames(q)',
            ...points.map(p => [
                `    p${p.label}_local = np.array([${this.fmt(p.x)}, ${this.fmt(p.y)}, ${this.fmt(p.z)}, 1.0])`,
                `    p${p.label} = T_frames[${p.frameIndex}] @ p${p.label}_local`,
            ].join('\n')),
            `    return {${points.map(p => `'${p.label}': p${p.label}[:3]`).join(', ')}}`,
        ].join('\n');

        return [
            '"""',
            'Forward kinematics + Jacobian - Craig DH convention',
            `Robot: ${rows.length} link(s), ${n} actuated joint(s)`,
            'Generated by DHViz',
            '"""',
            'import numpy as np',
            '', '',
            `def forward_kinematics(${n > 0 ? 'q' : ''}) -> np.ndarray:`,
            `    """4x4 homogeneous transform. q: array of ${n} joint variable(s)"""`,
            dhParams, '',
            matrices, '',
            chain,
            '    return T',
            framesCode,
            jacobianCode,
            pointsCode,
        ].join('\n');
    }

    symbolic(rows, points) {
        const n = this.actuatedCount(rows);
        const qSyms = Array.from({length: n}, (_, i) => `q${i+1}`);
        const symDecl = n > 0
            ? `    ${qSyms.join(', ')} = sp.symbols('${qSyms.join(' ')}')`
            : '    # No actuated joints';

        let qi = 1;
        const dhParams = rows.map((row, i) => {
            const isR = row.jointType === 'R';
            const isP = row.jointType === 'P';
            const lines = [`    # Link ${i+1} - ${isR ? 'Revolute' : 'Prismatic'}${row.actuated ? '' : ' (passive)'}`];
            lines.push(`    alpha${i} = sp.Rational(${Math.round(row.alpha * 1e6)}, 1000000)`);
            lines.push(`    a${i}     = sp.Rational(${Math.round(row.a * 1e6)}, 1000000)`);
            if (isP && row.actuated) {
                const off = Math.abs(row.d) < 1e-10 ? '' : ` + sp.Rational(${Math.round(row.d*1e6)}, 1000000)`;
                lines.push(`    d${i+1}     = q${qi}${off}`);
                lines.push(`    theta${i+1} = sp.Rational(${Math.round(row.theta*1e6)}, 1000000)`);
                qi++;
            } else if (isR && row.actuated) {
                lines.push(`    d${i+1}     = sp.Rational(${Math.round(row.d*1e6)}, 1000000)`);
                const off = Math.abs(row.theta) < 1e-10 ? '' : ` + sp.Rational(${Math.round(row.theta*1e6)}, 1000000)`;
                lines.push(`    theta${i+1} = q${qi}${off}`);
                qi++;
            } else {
                lines.push(`    d${i+1}     = sp.Rational(${Math.round(row.d*1e6)}, 1000000)`);
                lines.push(`    theta${i+1} = sp.Rational(${Math.round(row.theta*1e6)}, 1000000)`);
            }
            return lines.join('\n');
        }).join('\n\n');

        const matrices = rows.map((_, i) => [
            `    T${i}${i+1} = sp.Matrix([`,
            `        [ sp.cos(theta${i+1}),                  -sp.sin(theta${i+1}),                   0,       a${i}              ],`,
            `        [ sp.sin(theta${i+1})*sp.cos(alpha${i}), sp.cos(theta${i+1})*sp.cos(alpha${i}), -sp.sin(alpha${i}), -sp.sin(alpha${i})*d${i+1} ],`,
            `        [ sp.sin(theta${i+1})*sp.sin(alpha${i}), sp.cos(theta${i+1})*sp.sin(alpha${i}),  sp.cos(alpha${i}),  sp.cos(alpha${i})*d${i+1} ],`,
            `        [ 0,                                      0,                                      0,                  1                          ]`,
            `    ])`,
            `    T${i}${i+1} = sp.simplify(T${i}${i+1})`,
        ].join('\n')).join('\n\n');

        const chain = rows.length === 1
            ? `    T = T01`
            : `    T = T01\n` + rows.slice(1).map((_, i) => `    T = sp.simplify(T @ T${i+1}${i+2})`).join('\n');

        const jacobianSymCode = [
            '', '',
            'def jacobian_symbolic():',
            `    """Symbolic geometric Jacobian J(q) in R^(6x${rows.length})"""`,
            symDecl,
            '    frames = forward_kinematics_symbolic(return_frames=True)',
            `    o_n = frames[-1][:3, 3]`,
            `    Jv = sp.zeros(3, ${rows.length})`,
            `    Jw = sp.zeros(3, ${rows.length})`,
            ...rows.map((row, i) => [
                `    z${i} = frames[${i}][:3, 2]`,
                `    o${i} = frames[${i}][:3, 3]`,
                row.jointType === 'R'
                    ? `    Jv[:, ${i}] = sp.simplify(z${i}.cross(o_n - o${i}))\n    Jw[:, ${i}] = z${i}`
                    : `    Jv[:, ${i}] = z${i}\n    Jw[:, ${i}] = sp.zeros(3, 1)`,
            ].join('\n')),
            `    return sp.simplify(Jv.col_join(Jw))`,
        ].join('\n');

        const pointsCode = points.length === 0 ? '' : [
            '', '',
            'def point_positions_symbolic():',
            '    """Symbolic positions of reference points in base frame {0}"""',
            symDecl,
            '    T_frames = forward_kinematics_symbolic(return_frames=True)',
            ...points.map(p => [
                `    p${p.label}_local = sp.Matrix([${this.fmt(p.x)}, ${this.fmt(p.y)}, ${this.fmt(p.z)}, 1])`,
                `    p${p.label} = sp.simplify(T_frames[${p.frameIndex}] * p${p.label}_local)`,
            ].join('\n')),
            `    return {${points.map(p => `'${p.label}': p${p.label}[:3, 0]`).join(', ')}}`,
        ].join('\n');

        return [
            '"""',
            'Symbolic forward kinematics + Jacobian - Craig DH convention',
            `Robot: ${rows.length} link(s), ${n} actuated joint(s)`,
            'Requires: sympy',
            'Generated by DHViz',
            '"""',
            'import sympy as sp',
            '', '',
            'def forward_kinematics_symbolic(return_frames=False):',
            '    """Symbolic 4x4 homogeneous transform."""',
            symDecl, '',
            dhParams, '',
            matrices, '',
            chain,
            '    if return_frames:',
            '        frames = [sp.eye(4)]',
            ...rows.map((_, i) => `        frames.append(sp.simplify(frames[-1] @ T${i}${i+1}))`),
            '        return frames',
            '    return T',
            jacobianSymCode,
            pointsCode,
        ].join('\n');
    }
}

export default PythonExporter;